### ISSUE TITLE
Is readme not up to date ?

### ISSUE THREAD

**Issue by X901** [rebeloper/NavigationKit#8]
in your readme you said use 

NavigationKitView {
}

but when I use it it said isActive is required 
"Missing argument for parameter 'isActive' in call"

and also it show error 
"Cannot find type 'Navigation' in scope"
!!

**Comment by rebeloper** [comment]
Hi I have moved NavigationKit into SwiftUIPlus: https://github.com/rebeloper/SwiftUIPlus

Now you have only one View to call for all types of navigations: https://github.com/rebeloper/SwiftUIPlus/blob/main/Sources/SwiftUIPlus/Navigation/Page.swift

**Comment by X901** [comment]
Could you give me a full example ? 
I just won't to return to RootView from 4th view 
without re-build RootView
