### ISSUE TITLE
0.4.10 not working as in your documentation

### ISSUE THREAD

**Issue by afeefSohail** [rebeloper/NavigationKit#9]

**Comment by afeefSohail** [comment]
WTF bro your 0.4.10 version is diff from your Demo and your documentation explanation. nothing like your documentation and as like your demo project and you demo project can even running full of errors

**Comment by flopshot** [comment]
For those of you looking for another library, feel free to try [Navigator](https://github.com/flopshot/Navigator) (full disclosure: I am the author of this Navigation Library)

**Comment by rebeloper** [comment]
Please use these newer alternatives:
https://github.com/rebeloper/Dot/tree/main/Sources/Dot/Navigation
https://github.com/rebeloper/Dot/tree/main/Sources/Dot/NavigationStack

They are fully inline documented.
